
"use client";

import { useQuery } from "@tanstack/react-query";
import api from "@/lib/api";
import { Badge } from "@/components/ui/badge";

export default function GiftCodesList() {
    const { data, isLoading } = useQuery({
        queryKey: ["gift-codes"],
        queryFn: async () => {
            const res = await api.get("/subscriptions/gift-codes");
            return res.data.data;
        },
    });

    if (isLoading) return <p>Loading…</p>;

    return (
        <div className="space-y-4">
            <h2 className="text-xl font-semibold">Gift / Redeem Codes</h2>

            <div className="border rounded-lg overflow-hidden">
                <table className="w-full text-sm">
                    <thead className="bg-muted">
                        <tr>
                            <th className="p-2 text-left">Code</th>
                            <th className="p-2">Plan</th>
                            <th className="p-2">Assigned To</th>
                            <th className="p-2">Generated By</th>
                            <th className="p-2">Status</th>
                            <th className="p-2">Redeemed By</th>
                            <th className="p-2">Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.map((c: any) => (
                            <tr key={c.code} className="border-t">
                                <td className="p-2 font-mono">{c.code}</td>
                                <td className="p-2">{c.subscription_name}</td>

                                <td className="p-2">
                                    {c.assigned_user_name
                                        ? `${c.assigned_user_name} (${c.assigned_user_phone})`
                                        : "—"}
                                </td>

                                <td className="p-2">
                                    <Badge variant="secondary">
                                        {c.generated_by}
                                    </Badge>
                                </td>

                                <td className="p-2">
                                    {c.is_redeemed ? (
                                        <Badge variant="destructive">
                                            Redeemed
                                        </Badge>
                                    ) : (
                                        <Badge variant="success">
                                            Active
                                        </Badge>
                                    )}
                                </td>

                                <td className="p-2">
                                    {c.redeemed_user_name
                                        ? `${c.redeemed_user_name} (${c.redeemed_user_phone})`
                                        : "—"}
                                </td>

                                <td className="p-2 text-xs">
                                    {new Date(c.created_at).toLocaleDateString()}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
